tcdt:
  # need absolute path, org.hkmadao.tcdt.modules.generator.compsingle.CompSingleGenerator.generator
  project-path: D:\project-source\demo_jpa
  sys:
    authorized: true

server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /demo_jpa/**
  web:
    resources:
      static-locations: file:D:/project-source/demo_antd/dist
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo_jpa
    username: root
    password: 636ny5KUYNab7
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # update/none , 使用sqlite,不能使用自动建表
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        temp:
          user_jdbc_metadata_defaults: false

jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  rsa:
    path: D:/project-source/demo_jpa/src/main/resources
    privateKey: ${jwt.rsa.path}/private_key.pem
    publicKey: ${jwt.rsa.path}/public_key.pem
  expiration: 604800